export interface Quote { text: string; author: string }

export const QUOTES: Quote[] = [
  { text: "One who gains strength by overcoming obstacles possesses the only strength which can overcome adversity.", author: "Albert Schweitzer" },
  { text: "Gratitude makes sense of our past, brings peace for today, and creates a vision for tomorrow.", author: "Melody Beattie" },
  { text: "Action is the foundational key to all success.", author: "Pablo Picasso" },
  { text: "A little more persistence, a little more effort, and what seemed hopeless failure may turn to glorious success.", author: "Elbert Hubbard" },
  { text: "Action will remove the doubts that theory cannot solve.", author: "Tehyi Hsieh" },
  { text: "Your vision will become clear only when you look into your heart. Who looks outside, dreams. Who looks inside, awakens.", author: "Carl Jung" },
  { text: "A subtle thought that is in error may yet give rise to fruitful inquiry that can establish truths of great value.", author: "Isaac Asimov" },
  { text: "To give hope to someone occurs when you teach them how to use the tools to do it for themselves.", author: "Byron Pulsifer" },
  { text: "Let me tell you the secret that has led me to my goal: my strength lies solely in my tenacity", author: "Louis Pasteur" },
  { text: "If you let go a little, you will have a little peace. If you let go a lot, you will have a lot of peace.", author: "Ajahn Chah" },
  { text: "Life is a gift, and it offers us the privilege, opportunity, and responsibility to give something back by becoming more", author: "Anthony Robbins" },
  { text: "Strong people make as many mistakes as weak people. Difference is that strong people admit their mistakes, laugh at them, learn from them. That is how they become strong.", author: "Richard Needham" },
  { text: "A day of worry is more exhausting than a day of work.", author: "John Lubbock" },
  { text: "Where there is great love, there are always miracles.", author: "Willa Cather" },
  { text: "Every great advance in science has issued from a new audacity of the imagination.", author: "John Dewey" },
  { text: "Every action of our lives touches on some chord that will vibrate in eternity.", author: "Edwin Chapin" },
  { text: "Man cannot discover new oceans unless he has the courage to lose sight of the shore.", author: "Andr� Gide" },
  { text: "When performance exceeds ambition, the overlap is called success.", author: "Cullen Hightower" },
  { text: "The truth you believe and cling to makes you unavailable to hear anything new.", author: "Pema Chodron" },
  { text: "Everything that happens happens as it should, and if you observe carefully, you will find this to be so.", author: "Marcus Aurelius" },
  { text: "However many holy words you read, However many you speak, What good will they do you If you do not act on upon them?", author: "Buddha" },
  { text: "Those who will play with cats must expect to be scratched.", author: "Cervantes" },
  { text: "We cannot change our memories, but we can change their meaning and the power they have over us.", author: "David Seamans" },
  { text: "If facts are the seeds that later produce knowledge and wisdom, then the emotions and the impressions of the senses are the fertile soil in which the seeds must grow.", author: "Rachel Carson" },
  { text: "The best way to predict your future is to create it.", author: "Peter Drucker" },
  { text: "Be great in act, as you have been in thought.", author: "William Shakespeare" },
  { text: "It is not the possession of truth, but the success which attends the seeking after it, that enriches the seeker and brings happiness to him.", author: "Max Planck" },
  { text: "If there is no struggle, there is no progress.", author: "Frederick Douglass" },
  { text: "Great are they who see that spiritual is stronger than any material force, that thoughts rule the world.", author: "Ralph Emerson" },
  { text: "Sometimes our fate resembles a fruit tree in winter. Who would think that those branches would turn green again and blossom, but we hope it, we know it.", author: "Johann Wolfgang von Goethe" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { text: "A man may fulfil the object of his existence by asking a question he cannot answer, and attempting a task he cannot achieve.", author: "Oliver Holmes" },
  { text: "Once you choose hope, anythings possible.", author: "Christopher Reeve" },
  { text: "It is impossible for a man to learn what he thinks he already knows.", author: "Epictetus" },
  { text: "Know how to listen, and you will profit even from those who talk badly.", author: "Plutarch" },
  { text: "Stay away from what might have been and look at what will be.", author: "Marsha Petrie Sue" },
  { text: "Love is the flower you've got to let grow.", author: "John Lennon" },
  { text: "We can only learn to love by loving.", author: "Iris Murdoch" },
  { text: "Never do things others can do and will do, if there are things others cannot do or will not do.", author: "Amelia Earhart" },
  { text: "If you want your life to be more rewarding, you have to change the way you think.", author: "Oprah Winfrey" },
  { text: "Work for something because it is good, not just because it stands a chance to succeed.", author: "Vaclav Havel" },
  { text: "The true way to render ourselves happy is to love our work and find in it our pleasure.", author: "Francoise de Motteville" },
  { text: "We can do no great things, only small things with great love.", author: "Mother Teresa" },
  { text: "Good people are good because they've come to wisdom through failure. We get very little wisdom from success, you know.", author: "William Saroyan" },
  { text: "By living deeply in the present moment we can understand the past better and we can prepare for a better future.", author: "Thich Nhat Hanh" },
  { text: "The future is an opaque mirror. Anyone who tries to look into it sees nothing but the dim outlines of an old and worried face.", author: "Jim Bishop" },
  { text: "If we could see the miracle of a single flower clearly, our whole life would change.", author: "Buddha" },
  { text: "Difficulties are meant to rouse, not discourage. The human spirit is to grow strong by conflict.", author: "William Channing" },
  { text: "If the single man plant himself indomitably on his instincts, and there abide, the huge world will come round to him.", author: "Ralph Emerson" },
  { text: "To be able to give away riches is mandatory if you wish to possess them. This is the only way that you will be truly rich.", author: "Mahummad Ali" },
  { text: "Difficulties increase the nearer we get to the goal.", author: "Johann Wolfgang von Goethe" },
  { text: "The truth which has made us free will in the end make us glad also.", author: "Felix Adler" },
  { text: "No man is free who is not master of himself.", author: "Epictetus" },
  { text: "Ability will never catch up with the demand for it.", author: "Confucius" },
  { text: "Judge nothing, you will be happy. Forgive everything, you will be happier. Love everything, you will be happiest.", author: "Sri Chinmoy" },
  { text: "Great is the art of beginning, but greater is the art of ending.", author: "Lazurus Long" },
  { text: "Let go of your attachment to being right, and suddenly your mind is more open. You're able to benefit from the unique viewpoints of others, without being crippled by your own judgement.", author: "Ralph Marston" },
  { text: "You can be what you want to be. You have the power within and we will help you always.", author: "Byron Pulsifer" },
  { text: "You'll see it when you believe it.", author: "Wayne Dyer" },
  { text: "In the sky, there is no distinction of east and west; people create distinctions out of their own minds and then believe them to be true.", author: "Buddha" },
  { text: "I am like a falling star who has finally found her place next to another in a lovely constellation, where we will sparkle in the heavens forever.", author: "Amy Tan" },
  { text: "Never promise more than you can perform.", author: "Publilius Syrus" },
  { text: "It is the quality of our work which will please God, not the quantity.", author: "Mahatma Gandhi" },
  { text: "The best cure for the body is a quiet mind.", author: "Napoleon Bonaparte" },
  { text: "All men who have achieved great things have been great dreamers.", author: "Orison Marden" },
  { text: "The person who lives life fully, glowing with life's energy, is the person who lives a successful life.", author: "Daisaku Ikeda" },
  { text: "If you are going to achieve excellence in big things, you develop the habit in little matters. Excellence is not an exception, it is a prevailing attitude.", author: "Colin Powell" },
  { text: "Love is never lost. If not reciprocated, it will flow back and soften and purify the heart.", author: "Washington Irving" },
  { text: "Leaders aren't born they are made. And they are made just like anything else, through hard work. And that's the price well have to pay to achieve that goal, or any goal.", author: "Vince Lombardi" },
  { text: "People may doubt what you say, but they will believe what you do.", author: "Lewis Cass" },
  { text: "If one way be better than another, that you may be sure is natures way.", author: "Aristotle" },
  { text: "One faces the future with ones past.", author: "Pearl Buck" },
  { text: "Thousands of candles can be lit from a single, and the life of the candle will not be shortened. Happiness never decreases by being shared.", author: "Buddha" },
  { text: "Never put off till tomorrow what you can do today.", author: "Thomas Jefferson" },
  { text: "Imagination will often carry us to worlds that never were. But without it we go nowhere.", author: "Carl Sagan" },
  { text: "A leader is best when people barely know he exists, when his work is done, his aim fulfilled, they will say: we did it ourselves.", author: "Lao Tzu" },
  { text: "The secret of joy in work is contained in one word � excellence. To know how to do something well is to enjoy it.", author: "Pearl Buck" },
  { text: "Any of us can achieve virtue, if by virtue we merely mean the avoidance of the vices that do not attract us.", author: "Robert Lynd" },
  { text: "Sometimes the biggest act of courage is a small one.", author: "Lauren Raffo" },
  { text: "I don't believe in failure. It is not failure if you enjoyed the process.", author: "Oprah Winfrey" },
  { text: "Everything that exists is in a manner the seed of that which will be.", author: "Marcus Aurelius" },
  { text: "Some people thrive on huge, dramatic change. Some people prefer the slow and steady route. Do what's right for you.", author: "Julie Morgenstern" },
  { text: "Nothing diminishes anxiety faster than action.", author: "Walter Anderson" },
  { text: "Always do your best. What you plant now, you will harvest later.", author: "Og Mandino" },
  { text: "With courage you will dare to take risks, have the strength to be compassionate, and the wisdom to be humble. Courage is the foundation of integrity.", author: "Keshavan Nair" },
  { text: "Sometimes it is better to lose and do the right thing than to win and do the wrong thing.", author: "Tony Blair" },
  { text: "An invasion of armies can be resisted, but not an idea whose time has come.", author: "Victor Hugo" },
  { text: "Action may not always bring happiness, but there is no happiness without action.", author: "Benjamin Disraeli" },
  { text: "Love is the master key that opens the gates of happiness.", author: "Oliver Holmes" },
  { text: "Don't wait. The time will never be just right.", author: "Napoleon Hill" },
  { text: "We never understand how little we need in this world until we know the loss of it.", author: "James Barrie" },
  { text: "Our deepest wishes are whispers of our authentic selves. We must learn to respect them. We must learn to listen.", author: "Sarah Breathnach" },
  { text: "If you change the way you look at things, the things you look at change.", author: "Wayne Dyer" },
  { text: "Lots of people want to ride with you in the limo, but what you want is someone who will take the bus with you when the limo breaks down.", author: "Oprah Winfrey" },
  { text: "Most powerful is he who has himself in his own power.", author: "Seneca" },
  { text: "Life is like riding a bicycle. To keep your balance you must keep moving.", author: "Albert Einstein" },
  { text: "Experience keeps a dear school, but fools will learn in no other.", author: "Benjamin Franklin" },
  { text: "Successful people ask better questions, and as a result, they get better answers.", author: "Tony Robbins" },
  { text: "The universe is full of magical things, patiently waiting for our wits to grow sharper.", author: "Eden Phillpotts" },
  { text: "The person born with a talent they are meant to use will find their greatest happiness in using it.", author: "Johann Wolfgang von Goethe" },
  { text: "The greatest antidote to insecurity and the sense of fear is compassion � it brings one back to the basis of one's inner strength", author: "Dalai Lama" },
  { text: "In order to win, you must expect to win.", author: "Richard Bach" },
  { text: "Success means having the courage, the determination, and the will to become the person you believe you were meant to be.", author: "George Sheehan" },
  { text: "As we grow as unique persons, we learn to respect the uniqueness of others.", author: "Robert Schuller" },
  { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin Roosevelt" },
  { text: "My mama always said: life's like a box of chocolate � you never know what you gonna get.", author: "Forrest Gump" },
  { text: "Nobody will believe in you unless you believe in yourself.", author: "Liberace" },
  { text: "If we have a positive mental attitude, then even when surrounded by hostility, we shall not lack inner peace.", author: "Dalai Lama" },
  { text: "Either I will find a way, or I will make one.", author: "Philip Sidney" },
  { text: "Your mind will answer most questions if you learn to relax and wait for the answer.", author: "William Burroughs" },
  { text: "If the shoe doesn't fit, must we change the foot?", author: "Gloria Steinem" },
  { text: "The years teach much which the days never know.", author: "Ralph Emerson" },
  { text: "A goal without a plan is just a wish.", author: "Larry Elder" },
  { text: "You teach best what you most need to learn.", author: "Richard Bach" },
  { text: "What is new in the world? Nothing. What is old in the world? Nothing. Everything has always been and will always be.", author: "Sai Baba" },
  { text: "Self-complacency is fatal to progress.", author: "Margaret Sangster" },
  { text: "What the caterpillar calls the end of the world, the master calls a butterfly.", author: "Richard Bach" },
  { text: "Here is one quality that one must possess to win, and that is definiteness of purpose, the knowledge of what one wants, and a burning desire to possess it.", author: "Napoleon Hill" },
  { text: "Money was never a big motivation for me, except as a way to keep score. The real excitement is playing the game.", author: "Donald Trump" },
  { text: "The awareness of our own strength makes us modest.", author: "Paul Cezanne" },
  { text: "Courage is going from failure to failure without losing enthusiasm.", author: "Winston Churchill" },
  { text: "When I dare to be powerful, to use my strength in the service of my vision, then it becomes less and less important whether I am afraid.", author: "Audre Lorde" },
  { text: "Our doubts are traitors and make us lose the good we often might win, by fearing to attempt.", author: "Jane Addams" },
  { text: "We learn what we have said from those who listen to our speaking.", author: "Kenneth Patton" },
  { text: "He who deliberates fully before taking a step will spend his entire life on one leg.", author: "Chinese proverb" },
  { text: "If you don't know where you are going, you will probably end up somewhere else.", author: "Lawrence Peter" },
  { text: "Our kindness may be the most persuasive argument for that which we believe.", author: "Gordon Hinckley" },
  { text: "A man who doesn't trust himself can never really trust anyone else.", author: "Cardinal Retz" },
  { text: "People of mediocre ability sometimes achieve outstanding success because they don't know when to quit. Most men succeed because they are determined to.", author: "George Allen" },
  { text: "You're not obligated to win. You're obligated to keep trying to do the best you can every day.", author: "Marian Edelman" },
  { text: "Time changes everything except something within us which is always surprised by change.", author: "Thomas Hardy" },
  { text: "We need to find the courage to say NO to the things and people that are not serving us if we want to rediscover ourselves and live our lives with authenticity.", author: "Barbara De Angelis" },
  { text: "Compassion and happiness are not a sign of weakness but a sign of strength.", author: "Dalai Lama" },
  { text: "Do you want to know who you are? Don't ask. Act! Action will delineate and define you.", author: "Thomas Jefferson" },
  { text: "Do not give your attention to what others do or fail to do; give it to what you do or fail to do.", author: "Dhammapada" },
  { text: "No matter how hard the past, you can always begin again.", author: "Buddha" },
  { text: "Success is getting what you want. Happiness is wanting what you get.", author: "Dale Carnegie" },
  { text: "If you must tell me your opinions, tell me what you believe in. I have plenty of douts of my own.", author: "Johann Wolfgang von Goethe" },
  { text: "Great talent finds happiness in execution.", author: "Johann Wolfgang von Goethe" },
  { text: "Be faithful in small things because it is in them that your strength lies.", author: "Mother Teresa" },
  { text: "It is better to have enough ideas for some of them to be wrong, than to be always right by having no ideas at all.", author: "Edward de Bono" },
  { text: "Yesterday is history. Tomorrow is a mystery. And today? Today is a gift. That is why we call it the present.", author: "Babatunde Olatunji" },
  { text: "The most important thing is transforming our minds, for a new way of thinking, a new outlook: we should strive to develop a new inner world.", author: "Dalai Lama" },
  { text: "Adversity isn't set against you to fail; adversity is a way to build your character so that you can succeed over and over again through perseverance.", author: "Byron Pulsifer" },
  { text: "Be not afraid of greatness: some are born great, some achieve greatness, and some have greatness thrust upon them.", author: "William Shakespeare" },
  { text: "Great acts are made up of small deeds.", author: "Lao Tzu" },
  { text: "You will not be punished for your anger, you will be punished by your anger.", author: "Buddha" },
  { text: "Always be yourself, express yourself, have faith in yourself, do not go out and look for a successful personality and duplicate it.", author: "Bruce Lee" },
  { text: "I think somehow we learn who we really are and then live with that decision.", author: "Eleanor Roosevelt" },
  { text: "Without courage, wisdom bears no fruit.", author: "Baltasar Gracian" },
  { text: "A successful person is one who can lay a firm foundation with the bricks that others throw at him or her.", author: "David Brinkley" },
  { text: "If you seek truth you will not seek victory by dishonourable means, and if you find truth you will become invincible.", author: "Epictetus" },
  { text: "Most great people have attained their greatest success just one step beyond their greatest failure.", author: "Napoleon Hill" },
  { text: "Take time to deliberate, but when the time for action has arrived, stop thinking and go in.", author: "Napoleon Bonaparte" },
  { text: "Happiness is not in the mere possession of money; it lies in the joy of achievement, in the thrill of creative effort.", author: "Franklin Roosevelt" },
  { text: "If you do not change direction, you may end up where you are heading.", author: "Lao Tzu" },
  { text: "It is better to understand a little than to misunderstand a lot.", author: "Anatole France" },
  { text: "Courage is not about taking risks unknowingly but putting your own being in front of challenges that others may not be able to.", author: "Byron Pulsifer" },
  { text: "Nothing happens unless first we dream.", author: "Carl Sandburg" },
  { text: "The most dangerous way to lose time is not to spend it having fun, but to spend it doing fake work. When you spend time having fun, you know you're being self-indulgent.", author: "Paul Graham" },
  { text: "I cannot say whether things will get better if we change; what I can say is they must change if they are to get better.", author: "Georg Lichtenberg" },
  { text: "The road leading to a goal does not separate you from the destination; it is essentially a part of it.", author: "Charles DeLint" },
  { text: "We never live; we are always in the expectation of living.", author: "Voltaire" },
  { text: "Good actions give strength to ourselves and inspire good actions in others.", author: "Plato" },
  { text: "Society develops wit, but its contemplation alone forms genius.", author: "Madame de Stael" },
  { text: "For every failure, there's an alternative course of action. You just have to find it. When you come to a roadblock, take a detour.", author: "Mary Kay Ash" },
  { text: "This world, after all our science and sciences, is still a miracle; wonderful, inscrutable, magical and more, to whosoever will think of it.", author: "Thomas Carlyle" },
  { text: "Never, never, never give up.", author: "Winston Churchill" },
  { text: "Thousands of candles can be lighted from a single candle, and the life of the candle will not be shortened. Happiness never decreases by being shared.", author: "Buddha" },
  { text: "To change ones life, start immediately, do it flamboyantly, no exceptions.", author: "William James" },
  { text: "To accomplish great things, we must dream as well as act.", author: "Anatole France" },
  { text: "No matter how carefully you plan your goals they will never be more that pipe dreams unless you pursue them with gusto.", author: "W. Clement Stone" },
  { text: "If we could learn to like ourselves, even a little, maybe our cruelties and angers might melt away.", author: "John Steinbeck" },
  { text: "You have to believe in yourself.", author: "Sun Tzu" },
  { text: "Never doubt that a small group of thoughtful, committed people can change the world. Indeed. It is the only thing that ever has.", author: "Margaret Mead" },
  { text: "Neither genius, fame, nor love show the greatness of the soul. Only kindness can do that.", author: "Jean Lacordaire" },
  { text: "A wise man can learn more from a foolish question than a fool can learn from a wise answer.", author: "Bruce Lee" },
  { text: "Success in business requires training and discipline and hard work. But if you're not frightened by these things, the opportunities are just as great today as they ever were.", author: "David Rockefeller" },
  { text: "Without passion man is a mere latent force and possibility, like the flint which awaits the shock of the iron before it can give forth its spark.", author: "Amiel" },
  { text: "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", author: "Albert Schweitzer" },
  { text: "More often than not, anger is actually an indication of weakness rather than of strength.", author: "Dalai Lama" },
  { text: "Without this playing with fantasy no creative work has ever yet come to birth. The debt we owe to the play of the imagination is incalculable.", author: "Carl Jung" },
  { text: "All action results from thought, so it is thoughts that matter.", author: "Sai Baba" },
  { text: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein" },
  { text: "There is no great genius without some touch of madness.", author: "Seneca" },
  { text: "I do not believe in a fate that falls on men however they act; but I do believe in a fate that falls on them unless they act.", author: "Buddha" },
  { text: "Be the change that you want to see in the world.", author: "Mohandas Gandhi" },
  { text: "If you're walking down the right path and you're willing to keep walking, eventually you'll make progress.", author: "Barack Obama" },
  { text: "Sometimes the cards we are dealt are not always fair. However you must keep smiling and moving on.", author: "Tom Jackson" },
  { text: "Only those who dare to fail greatly can ever achieve greatly.", author: "Robert Kennedy" },
  { text: "You must welcome change as the rule but not as your ruler.", author: "Denis Waitley" },
  { text: "He that never changes his opinions, never corrects his mistakes, and will never be wiser on the morrow than he is today.", author: "Tryon Edwards" },
  { text: "Learning is a treasure that will follow its owner everywhere", author: "Chinese proverb" },
  { text: "Time is the most valuable thing a man can spend.", author: "Theophrastus" },
  { text: "Failure will never overtake me if my determination to succeed is strong enough.", author: "Og Mandino" },
  { text: "It is not the mistake that has the most power, instead, it is learning from the mistake to advance your own attributes.", author: "Byron Roberts" },
  { text: "You may say Im a dreamer, but Im not the only one, I hope someday you will join us, and the world will live as one.", author: "John Lennon" },
  { text: "Many people think of prosperity that concerns money only to forget that true prosperity is of the mind.", author: "Byron Pulsifer" },
  { text: "If your actions inspire others to dream more, learn more, do more and become more, you are a leader.", author: "John Quincy Adams" },
  { text: "The art of progress is to preserve order amid change, and to preserve change amid order.", author: "Alfred Whitehead" },
  { text: "Strength to carry on despite the odds means you have faith in your own abilities and know how.", author: "Byron Pulsifer" },
  { text: "Never mistake activity for achievement.", author: "John Wooden" },
  { text: "Today, give a stranger a smile without waiting for it may be the joy they need to have a great day.", author: "Byron Pulsifer" },
  { text: "The poor man is not he who is without a cent, but he who is without a dream.", author: "Harry Kemp" },
  { text: "Who we are never changes. Who we think we are does.", author: "Mary Almanac" },
  { text: "With the realization of ones own potential and self-confidence in ones ability, one can build a better world.", author: "Dalai Lama" },
  { text: "Continuous effort梟ot strength or intelligence梚s the key to unlocking our potential.", author: "Winston Churchill" },
  { text: "A wise man will make more opportunities than he finds.", author: "Francis Bacon" },
  { text: "Learn from yesterday, live for today, hope for tomorrow.", author: "Albert Einstein" },
  { text: "There is one thing you have got to learn about our movement. Three people are better than no people.", author: "Fannie Hamer" },
  { text: "Nature is a mutable cloud which is always and never the same.", author: "Ralph Emerson" },
  { text: "Try not to become a man of success, but rather try to become a man of value.", author: "Albert Einstein" },
  { text: "It is on our failures that we base a new and different and better success.", author: "Havelock Ellis" },
  { text: "Do not be embarrassed by your mistakes. Nothing can teach us better than our understanding of them. This is one of the best ways of self-education.", author: "Thomas Carlyle" },
  { text: "Life is so constructed that an event does not, cannot, will not, match the expectation.", author: "Charlotte Bronte" },
  { text: "Our lives are the only meaningful expression of what we believe and in Whom we believe. And the only real wealth, for any of us, lies in our faith.", author: "Gordon Hinckley" },
  { text: "Everyone has been made for some particular work, and the desire for that work has been put in every heart.", author: "Rumi" },
  { text: "Everyone should carefully observe which way his heart draws him, and then choose that way with all his strength.", author: "Hasidic saying" },
  { text: "Nothing could be worse than the fear that one had given up too soon, and left one unexpended effort that might have saved the world.", author: "Jane Addams" },
  { text: "Never mistake motion for action.", author: "Ernest Hemingway" },
  { text: "Chance is always powerful. Let your hook be always cast; in the pool where you least expect it, there will be a fish.", author: "Ovid" },
  { text: "Go for it now. The future is promised to no one.", author: "Wayne Dyer" },
  { text: "Do not overrate what you have received, nor envy others. He who envies others does not obtain peace of mind.", author: "Buddha" },
  { text: "The undertaking of a new action brings new strength.", author: "Richard Evans" },
  { text: "One does not discover new lands without consenting to lose sight of the shore for a very long time.", author: "Andr� Gide" },
  { text: "The most successful people are those who are good at plan B.", author: "James Yorke" },
  { text: "Bold is not the act of foolishness but the attribute and inner strength to act when others will not so as to move forward not backward.", author: "Byron Pulsifer" },
  { text: "Those who try to do something and fail are infinitely better than those who try nothing and succeed.", author: "Lloyd Jones" },
  { text: "Character cannot be developed in ease and quiet. Only through experience of trial and suffering can the soul be strengthened, vision cleared, ambition inspired, and success achieved.", author: "Helen Keller" },
  { text: "Keep true to the dreams of thy youth.", author: "Friedrich von Schiller" },
  { text: "I cannot give you the formula for success, but I can give you the formula for failure: which is: Try to please everybody.", author: "Herbert Swope" },
  { text: "I don't believe in failure. It's not failure if you enjoyed the process.", author: "Oprah Winfrey" },
  { text: "There are basically two types of people. People who accomplish things, and people who claim to have accomplished things. The first group is less crowded.", author: "Mark Twain" },
  { text: "Dreams pass into the reality of action. From the actions stems the dream again; and this interdependence produces the highest form of living.", author: "Anais Nin" },
  { text: "While we stop to think, we often miss our opportunity.", author: "Publilius Syrus" },
  { text: "The smallest flower is a thought, a life answering to some feature of the Great Whole, of whom they have a persistent intuition.", author: "Honore de Balzac" },
  { text: "There are two kinds of failures: those who thought and never did, and those who did and never thought.", author: "Laurence J. Peter" },
  { text: "Change in all things is sweet.", author: "Aristotle" },
  { text: "One fails forward toward success.", author: "Charles Kettering" },
  { text: "It is fatal to enter any war without the will to win it.", author: "General Douglas MacArthur" },
  { text: "We do not quit playing because we grow old, we grow old because we quit playing.", author: "Oliver Holmes" },
  { text: "The self is not something ready-made, but something in continuous formation through choice of action.", author: "John Dewey" },
  { text: "One needs something to believe in, something for which one can have whole-hearted enthusiasm. One needs to feel that ones life has meaning, that one is needed in this world.", author: "Hannah Senesh" },
  { text: "The only person who never makes mistakes is the person who never does anything.", author: "Denis Waitley" },
  { text: "Absence makes the heart grow fonder.", author: "Haynes Bayly" },
  { text: "Give it all you've got because you never know if there's going to be a next time.", author: "Danielle Ingrum" },
  { text: "The best thing in every noble dream is the dreamer...", author: "Moncure Conway" },
  { text: "Look forward to spring as a time when you can start to see what nature has to offer once again.", author: "Byron Pulsifer" },
  { text: "Through perseverance many people win success out of what seemed destined to be certain failure.", author: "Benjamin Disraeli" },
  { text: "Try not to become a man of success but rather try to become a man of value.", author: "Albert Einstein" },
  { text: "Yesterdays home runs don't win today's games.", author: "Babe Ruth" },
  { text: "If I am not for myself, who will be for me? If I am not for others, what am I? And if not now, when?", author: "Rabbi Hillel" },
  { text: "It is never too late to be what you might have been.", author: "George Eliot" },
  { text: "To give ones self earnestly to the duties due to men, and, while respecting spiritual beings, to keep aloof from them, may be called wisdom.", author: "Confucius" },
  { text: "We must learn our limits. We are all something, but none of us are everything.", author: "Blaise Pascal" },
  { text: "I'm a great believer in luck and I find the harder I work, the more I have of it.", author: "Thomas Jefferson" },
  { text: "Progress always involves risks. You can't steal second base and keep your foot on first.", author: "Frederick Wilcox" },
  { text: "Mediocrity knows nothing higher than itself, but talent instantly recognizes genius.", author: "Arthur Conan Doyle" },
  { text: "Follow effective action with quiet reflection. From the quiet reflection will come even more effective action.", author: "Peter Drucker" },
  { text: "Until you value yourself, you won't value your time. Until you value your time, you won't do anything with it.", author: "M. Scott Peck" },
  { text: "It is the mark of an educated mind to be able to entertain a thought without accepting it.", author: "Aristotle" },
  { text: "Take no thought of who is right or wrong or who is better than. Be not for or against.", author: "Bruce Lee" },
  { text: "I am not afraid of tomorrow, for I have seen yesterday and I love today.", author: "William White" },
  { text: "There is nothing impossible to him who will try.", author: "Alexander the Great" },
  { text: "Time you enjoyed wasting was not wasted.", author: "John Lennon" },
  { text: "There are no limitations to the mind except those we acknowledge.", author: "Napoleon Hill" },
  { text: "If you'll not settle for anything less than your best, you will be amazed at what you can accomplish in your lives.", author: "Vince Lombardi" },
  { text: "If you can dream it, you can do it.", author: "Walt Disney" },
  { text: "We can change our lives. We can do, have, and be exactly what we wish.", author: "Tony Robbins" },
  { text: "One secret of success in life is for a man to be ready for his opportunity when it comes.", author: "Benjamin Disraeli" },
  { text: "Think like a man of action; act like a man of thought.", author: "Henri L. Bergson" },
  { text: "Never bend your head. Always hold it high. Look the world right in the eye.", author: "Helen Keller" },
  { text: "Wherever a man may happen to turn, whatever a man may undertake, he will always end up by returning to the path which nature has marked out for him.", author: "Johann Wolfgang von Goethe" },
  { text: "Nothing great was ever achieved without enthusiasm.", author: "Ralph Emerson" },
  { text: "To understand the heart and mind of a person, look not at what he has already achieved, but at what he aspires to do.", author: "Kahlil Gibran" },
  { text: "The man who trusts men will make fewer mistakes than he who distrusts them.", author: "Cavour" },
  { text: "The mark of your ignorance is the depth of your belief in injustice and tragedy. What the caterpillar calls the end of the world, the Master calls the butterfly.", author: "Richard Bach" },
  { text: "Let the future tell the truth, and evaluate each one according to his work and accomplishments. The present is theirs; the future, for which I have really worked, is mine.", author: "Nikola Tesla" },
  { text: "If you are patient in one moment of anger, you will escape one hundred days of sorrow.", author: "Chinese proverb" },
  { text: "The truest greatness lies in being kind, the truest wisdom in a happy mind.", author: "Ella Wilcox" },
  { text: "Fear not for the future, weep not for the past.", author: "Percy Shelley" },
  { text: "The two most powerful warriors are patience and time.", author: "Leo Tolstoy" },
  { text: "The reason most goals are not achieved is that we spend our time doing second things first.", author: "Robert McKain" },
  { text: "All that we are is the result of what we have thought. The mind is everything. What we think we become.", author: "Buddha" },
  { text: "The only thing to do with good advice is to pass it on. It is never of any use to oneself.", author: "Oscar Wilde" },
  { text: "Never tell a young person that anything cannot be done. God may have been waiting centuries for someone ignorant enough of the impossible to do that very thing.", author: "John Holmes" },
  { text: "Thats the risk you take if you change: that people you've been involved with won't like the new you. But other people who do will come along.", author: "Lisa Alther" },
  { text: "Your attitude, not your aptitude, will determine your altitude.", author: "Zig Ziglar" },
  { text: "Mind is everything: muscle, pieces of rubber. All that I am, I am because of my mind.", author: "Paavo Nurmi" },
  { text: "For success, attitude is equally as important as ability.", author: "Harry Banks" },
  { text: "Into each life rain must fall but rain can be the giver of life and it is all in your attitude that makes rain produce sunshine.", author: "Byron Pulsifer" },
  { text: "Fear of failure is one attitude that will keep you at the same point in your life.", author: "Byron Pulsifer" },
  { text: "Let your hook always be cast; in the pool where you least expect it, there will be a fish.", author: "Ovid" },
  { text: "The greatest mistake you can make in life is to be continually fearing you will make one.", author: "Elbert Hubbard" },
  { text: "The time you think you're missing, misses you too.", author: "Ymber Delecto" },
  { text: "Each day can be one of triumph if you keep up your interests.", author: "George Matthew Adams" },
  { text: "The first requisite for success is the ability to apply your physical and mental energies to one problem incessantly without growing weary.", author: "Thomas Edison" },
  { text: "The thing always happens that you really believe in; and the belief in a thing makes it happen.", author: "Frank Wright" },
  { text: "Never idealize others. They will never live up to your expectations.", author: "Leo Buscaglia" },
  { text: "All great achievements require time.", author: "Maya Angelou" },
  { text: "Make it a rule of life never to regret and never to look back. Regret is an appalling waste of energy; you can't build on it; it's only for wallowing in.", author: "Katherine Mansfield" },
  { text: "Appreciation can make a day, even change a life. Your willingness to put it into words is all that is necessary.", author: "Margaret Cousins" },
  { text: "To see things in the seed, that is genius.", author: "Lao Tzu" },
  { text: "Time stays long enough for anyone who will use it.", author: "Leonardo da Vinci" },
  { text: "To make no mistakes is not in the power of man; but from their errors and mistakes the wise and good learn wisdom for the future.", author: "Plutarch" },
  { text: "I believe that every person is born with talent.", author: "Maya Angelou" },
  { text: "It is surprising what a man can do when he has to, and how little most men will do when they don't have to.", author: "Walter Linn" },
  { text: "You have power over your mind � not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius" },
  { text: "Give me six hours to chop down a tree and I will spend the first four sharpening the axe.", author: "Abraham Lincoln" },
  { text: "To free us from the expectations of others, to give us back to ourselves � there lies the great, singular power of self-respect.", author: "Joan Didion" },
  { text: "I think you can have moderate success by copying something else, but if you really want to knock it out of the park, you have to do something different and take chances.", author: "Lee Womack" },
  { text: "To succeed, we must first believe that we can.", author: "Michael Korda" },
  { text: "Never apologize for showing feelings. When you do so, you apologize for the truth.", author: "Benjamin Disraeli" },
  { text: "All things change; nothing perishes.", author: "Ovid" },
  { text: "When your desires are strong enough you will appear to possess superhuman powers to achieve.", author: "Napoleon Hill" },
  { text: "What you fear is that which requires action to overcome.", author: "Byron Pulsifer" },
  { text: "Change is the law of life. And those who look only to the past or present are certain to miss the future.", author: "John Kennedy" },
  { text: "You can't stop the waves, but you can learn to surf.", author: "Jon Kabat-Zinn" },
  { text: "Until you make peace with who you are, you'll never be content with what you have.", author: "Doris Mortman" },
  { text: "Formula for success: under promise and over deliver.", author: "Tom Peters" },
  { text: "No valid plans for the future can be made by those who have no capacity for living now.", author: "Alan Watts" },
  { text: "There is never enough time to do everything, but there is always enough time to do the most important thing.", author: "Brian Tracy" },
  { text: "Try and fail, but don't fail to try.", author: "Stephen Kaggwa" },
  { text: "Never say there is nothing beautiful in the world any more. There is always something to make you wonder in the shape of a tree, the trembling of a leaf.", author: "Albert Schweitzer" },
  { text: "You are never given a wish without also being given the power to make it come true. You may have to work for it, however.", author: "Richard Bach" },
  { text: "Six essential qualities that are the key to success: Sincerity, personal integrity, humility, courtesy, wisdom, charity.", author: "William Menninger" },
  { text: "You might well remember that nothing can bring you success but yourself.", author: "Napoleon Hill" },
  { text: "Happiness is as a butterfly which, when pursued, is always beyond our grasp, but which if you will sit down quietly, may alight upon you.", author: "Nathaniel Hawthorne" },
  { text: "Waste no more time arguing about what a good man should be. Be one.", author: "Marcus Aurelius" },
  { text: "You really can change the world if you care enough.", author: "Marian Edelman" },
  { text: "Better be ignorant of a matter than half know it.", author: "Publilius Syrus" },
  { text: "Be the chief but never the lord.", author: "Lao Tzu" },
  { text: "He who is fixed to a star does not change his mind.", author: "Leonardo da Vinci" },
  { text: "I have often regretted my speech, never my silence.", author: "Publilius Syrus" },
  { text: "Don't wait for your feelings to change to take the action. Take the action and your feelings will change.", author: "Barbara Baron" },
  { text: "Trouble is only opportunity in work clothes.", author: "Henry J. Kaiser" },
  { text: "There is only one way to happiness and that is to cease worrying about things which are beyond the power of our will.", author: "Epictetus" },
  { text: "You get peace of mind not by thinking about it or imagining it, but by quietening and relaxing the restless mind.", author: "Remez Sasson" },
  { text: "Transformation does not start with some one else changing you; transformation is an inner self reworking of what you are now to what you will be.", author: "Byron Pulsifer" },
  { text: "Chaos is inherent in all compounded things. Strive on with diligence.", author: "Buddha" },
  { text: "Never deny a diagnosis, but do deny the negative verdict that may go with it.", author: "Norman Cousins" },
  { text: "If you love life, don't waste time, for time is what life is made up of.", author: "Bruce Lee" },
  { text: "The key to transforming our hearts and minds is to have an understanding of how our thoughts and emotions work.", author: "Dalai Lama" },
  { text: "Rather than wishing for change, you first must be prepared to change.", author: "Catherine Pulsifer" },
  { text: "To exist is to change, to change is to mature, to mature is to go on creating oneself endlessly.", author: "Henri Bergson" },
  { text: "If you take each challenge one step at a time, with faith in every footstep, your strength and understanding will increase.", author: "James Faust" },
  { text: "The past has no power to stop you from being present now. Only your grievance about the past can do that.", author: "Eckhart Tolle" },
  { text: "Choose a job you love, and you will never have to work a day in your life.", author: "Confucius" },
  { text: "I never think of the future. It comes soon enough.", author: "Albert Einstein" },
  { text: "Good thoughts are no better than good dreams, unless they be executed.", author: "Ralph Emerson" },
  { text: "Silences make the real conversations between friends. Not the saying but the never needing to say is what counts.", author: "Margaret Runbeck" },
  { text: "Your work is to discover your work and then with all your heart to give yourself to it.", author: "Buddha" },
  { text: "Positive thinking will let you do everything better than negative thinking will.", author: "Zig Ziglar" },
  { text: "Logic will get you from A to B. Imagination will take you everywhere.", author: "Albert Einstein" },
  { text: "Your work is to discover your world and then with all your heart give yourself to it.", author: "Buddha" },
  { text: "Slow down and everything you are chasing will come around and catch you.", author: "John De Paola" },
  { text: "Do not be too timid and squeamish about your reactions. All life is an experiment. The more experiments you make the better.", author: "Ralph Emerson" },
  { text: "Thought is the blossom; language the bud; action the fruit behind it.", author: "Ralph Emerson" },
  { text: "Constant kindness can accomplish much. As the sun makes ice melt, kindness causes misunderstanding, mistrust, and hostility to evaporate.", author: "Albert Schweitzer" },
  { text: "There are two ways to slide easily through life: to believe everything or to doubt everything; both ways save us from thinking.", author: "Alfred Korzybski" },
  { text: "To know oneself is to study oneself in action with another person.", author: "Bruce Lee" },
  { text: "It is not so important to know everything as to appreciate what we learn.", author: "Hannah More" },
  { text: "The industrial landscape is already littered with remains of once successful companies that could not adapt their strategic vision to altered conditions of competition.", author: "Abernathy" },
  { text: "The future is completely open, and we are writing it moment to moment.", author: "Pema Chodron" },
  { text: "He who knows that enough is enough will always have enough.", author: "Lao Tzu" },
  { text: "Obstacles are those things you see when you take your eyes off the goal.", author: "Hannah More" },
  { text: "Lose an hour in the morning, and you will spend all day looking for it.", author: "Richard Whately" },
  { text: "Your future depends on many things, but mostly on you.", author: "Frank Tyger" },
  { text: "Life is change. Growth is optional. Choose wisely.", author: "Karen Clark" },
  { text: "Doing nothing is better than being busy doing nothing.", author: "Lao Tzu" },
  { text: "Kind words will unlock an iron door.", author: "Turkish proverb" },
  { text: "Keep silence for the most part, and speak only when you must, and then briefly.", author: "Epictetus" },
  { text: "Arrogance and rudeness are training wheels on the bicycle of life � for weak people who cannot keep their balance without them.", author: "Laura Teresa Marquez" },
  { text: "An idea that is developed and put into action is more important than an idea that exists only as an idea.", author: "Buddha" },
  { text: "You may be deceived if you trust too much, but you will live in torment if you don't trust enough.", author: "Frank Crane" },
  { text: "Look back over the past, with its changing empires that rose and fell, and you can foresee the future, too.", author: "Marcus Aurelius" },
  { text: "All difficult things have their origin in that which is easy, and great things in that which is small.", author: "Lao-Tzu" },
  { text: "Work while you have the light. You are responsible for the talent that has been entrusted to you.", author: "Henri-Frederic Amiel" },
  { text: "No person is your friend who demands your silence, or denies your right to grow.", author: "Alice Walker" },
  { text: "Better than a thousand hollow words is one word that brings peace.", author: "Buddha" },
  { text: "Self-trust is the first secret of success.", author: "Ralph Emerson" },
  { text: "To be great is to be misunderstood.", author: "Ralph Emerson" },
  { text: "Don't turn away from possible futures before you're certain you don't have anything to learn from them.", author: "Richard Bach" },
  { text: "There never was a good knife made of bad steel.", author: "Benjamin Franklin" },
  { text: "The pessimist sees difficulty in every opportunity. The optimist sees the opportunity in every difficulty.", author: "Winston Churchill" },
  { text: "I believe in one thing only, the power of human will.", author: "Joseph Stalin" },
  { text: "Silence is deep as Eternity, Speech is shallow as Time.", author: "Carlyle" },
  { text: "Kind words do not cost much. Yet they accomplish much.", author: "Blaise Pascal" },
  { text: "I believe that we are solely responsible for our choices, and we have to accept the consequences of every deed, word, and thought throughout our lifetime.", author: "Elisabeth Kubler-Ross" },
  { text: "The superior man acts before he speaks, and afterwards speaks according to his action.", author: "Confucius" },
  { text: "The greatest discovery of our generation is that human beings can alter their lives by altering their attitudes of mind. As you think, so shall you be.", author: "William James" },
  { text: "Excellence is not a skill. It is an attitude.", author: "Ralph Marston" },
  { text: "The greater part of human pain is unnecessary. It is self-created as long as the unobserved mind runs your life.", author: "Eckhart Tolle" },
  { text: "Consider how hard it is to change yourself and you'll understand what little chance you have in trying to change others.", author: "Jacob Braude" },
  { text: "The spirit, the will to win, and the will to excel, are the things that endure. These qualities are so much more important than the events that occur.", author: "Vincent Lombardi" },
  { text: "Light tomorrow with today!", author: "Elizabeth Browning" },
  { text: "There is a way that nature speaks, that land speaks. Most of the time we are simply not patient enough, quiet enough, to pay attention to the story.", author: "Linda Hogan" },
  { text: "I never worry about action, but only inaction.", author: "Winston Churchill" },
  { text: "How wonderful that we have met with a paradox. Now we have some hope of making progress.", author: "Niels Bohr" },
  { text: "Time you enjoy wasting, was not wasted.", author: "John Lennon" },
  { text: "The greatest pleasure I know is to do a good action by stealth, and to have it found out by accident.", author: "Charles Lamb" },
  { text: "Build a better mousetrap and the world will beat a path to your door.", author: "Ralph Emerson" },
  { text: "We must overcome the notion that we must be regular. It robs you of the chance to be extraordinary and leads you to the mediocre.", author: "Uta Hagen" },
  { text: "Ability is what you're capable of doing. Motivation determines what you do.Attitude determines how well you do it.", author: "Lou Holtz" },
  { text: "The trick is in what one emphasizes. We either make ourselves miserable, or we make ourselves happy. The amount of work is the same.", author: "Carlos Castaneda" },
  { text: "What we think determines what happens to us, so if we want to change our lives, we need to stretch our minds.", author: "Wayne Dyer" },
  { text: "If you lose today, win tomorrow. In this never-ending spirit of challenge is the heart of a victor.", author: "Daisaku Ikeda" },
  { text: "I am always doing that which I can not do, in order that I may learn how to do it.", author: "Pablo Picasso" },
  { text: "There is no scarcity of opportunity to make a living at what you love; theres only scarcity of resolve to make it happen.", author: "Wayne Dyer" },
  { text: "A thing well said will be wit in all languages.", author: "John Dryden" },
  { text: "Better than a thousand hollow words, is one word that brings peace.", author: "Buddha" },
  { text: "To follow, without halt, one aim: There is the secret of success.", author: "Anna Pavlova" },
  { text: "The beginning is always today.", author: "Mary Wollstonecraft" },
  { text: "We are shaped by our thoughts; we become what we think. When the mind is pure, joy follows like a shadow that never leaves.", author: "Buddha" },
  { text: "Turn your face toward the sun and the shadows will fall behind you.", author: "Maori proverb" },
  { text: "Do not turn back when you are just at the goal.", author: "Publilius Syrus" },
  { text: "Your big opportunity may be right where you are now.", author: "Napoleon Hill" },
  { text: "Love vanquishes time. To lovers, a moment can be eternity, eternity can be the tick of a clock.", author: "Mary Parrish" },
  { text: "Our passion is our strength.", author: "Billie Armstrong" },
  { text: "To dream of the person you would like to be is to waste the person you are.", author: "Tim Menchen" },
  { text: "I believe that we are fundamentally the same and have the same basic potential.", author: "Dalai Lama" },
  { text: "The most precious gift we can offer anyone is our attention. When mindfulness embraces those we love, they will bloom like flowers.", author: "Thich Nhat Hanh" },
  { text: "As we risk ourselves, we grow. Each new experience is a risk.", author: "Fran Watson" },
  { text: "Time is not a measure the length of a day or month or year but more a measure of what you have accomplished.", author: "Byron Pulsifer" },
  { text: "Courage is not the absence of fear, but simply moving on with dignity despite that fear.", author: "Pat Riley" },
  { text: "You can do it if you believe you can!", author: "Napoleon Hill" },
  { text: "Great ideas often receive violent opposition from mediocre minds.", author: "Albert Einstein" },
  { text: "Everyone can taste success when the going is easy, but few know how to taste victory when times get tough.", author: "Byron Pulsifer" },
  { text: "Obstacles are those frightful things you see when you take your eyes off your goal.", author: "Henry Ford" },
  { text: "Decision is a risk rooted in the courage of being free.", author: "Paul Tillich" },
  { text: "Everything that irritates us about others can lead us to a better understanding of ourselves.", author: "Carl Jung" },
  { text: "Promises are the uniquely human way of ordering the future, making it predictable and reliable to the extent that this is humanly possible.", author: "Hannah Arendt" },
  { text: "Meaning is not what you start with but what you end up with.", author: "Peter Elbow" },
  { text: "The greatest barrier to success is the fear of failure.", author: "Eriksson" },
  { text: "I know but one freedom and that is the freedom of the mind.", author: "Antoine de Saint-Exupery" },
  { text: "They can conquer who believe they can.", author: "Virgil" },
  { text: "If you focus on results, you will never change. If you focus on change, you will get results.", author: "Jack Dixon" },
  { text: "If you spend your whole life waiting for the storm, you'll never enjoy the sunshine.", author: "Morris West" },
  { text: "Using the power of decision gives you the capacity to get past any excuse to change any and every part of your life in an instant.", author: "Tony Robbins" },
  { text: "Just trust yourself, then you will know how to live.", author: "Goethe" },
  { text: "One today is worth two tomorrows.", author: "Benjamin Franklin" },
  { text: "Our ability to achieve happiness and success depends on the strength of our wings.", author: "Catherine Pulsifer" },
  { text: "Whoever is happy will make others happy, too.", author: "Mark Twain" },
  { text: "I can't imagine a person becoming a success who doesn't give this game of life everything hes got.", author: "Walter Cronkite" },
  { text: "Live through feeling and you will live through love. For feeling is the language of the soul, and feeling is truth.", author: "Matt Zotti" },
  { text: "Strength does not come from physical capacity. It comes from an indomitable will.", author: "Mahatma Gandhi" },
  { text: "If you light a lamp for somebody, it will also brighten your path.", author: "Buddha" },
  { text: "Weve got to have a dream if we are going to make a dream come true.", author: "Walt Disney" },
  { text: "There is nothing happens to any person but what was in his power to go through with.", author: "Marcus Aurelius" },
  { text: "Forget about all the reasons why something may not work. You only need to find one good reason why it will.", author: "Robert Anthony" },
  { text: "Being angry never solves anything.", author: "Catherine Pulsifer" },
  { text: "Better to have loved and lost, than to have never loved at all.", author: "St. Augustine" },
  { text: "When you learn, teach. When you get, give.", author: "Maya Angelou" },
  { text: "Blessed is the man who expects nothing, for he shall never be disappointed.", author: "Alexander Pope" },
  { text: "We shall never know all the good that a simple smile can do.", author: "Mother Teresa" },
  { text: "The world has the habit of making room for the man whose actions show that he knows where he is going.", author: "Napoleon Hill" },
  { text: "First comes thought; then organization of that thought, into ideas and plans; then transformation of those plans into reality. The beginning, as you will observe, is in your imagination.", author: "Napoleon Hill" },
  { text: "Silence is a source of great strength.", author: "Lao Tzu" },
  { text: "The longer we dwell on our misfortunes, the greater is their power to harm us.", author: "Voltaire" },
  { text: "Nothing is at last sacred but the integrity of your own mind.", author: "Ralph Emerson" },
  { text: "The eye sees only what the mind is prepared to comprehend.", author: "Henri Bergson" },
  { text: "The person who makes a success of living is the one who see his goal steadily and aims for it unswervingly. That is dedication.", author: "Cecil B. DeMille" },
  { text: "Edison failed 10,000 times before he made the electric light. Do not be discouraged if you fail a few times.", author: "Napoleon Hill" },
  { text: "If A is success in life, then A equals x plus y plus z. Work is x; y is play; and z is keeping your mouth shut.", author: "Albert Einstein" },
  { text: "We could never learn to be brave and patient if there were only joy in the world.", author: "Helen Keller" },
  { text: "To accomplish great things, we must not only act, but also dream; not only plan, but also believe.", author: "Anatole France" },
  { text: "Action may not always bring happiness; but there is no happiness without action.", author: "Benjamin Disraeli" },
  { text: "We are all faced with a series of great opportunities brilliantly disguised as impossible situations.", author: "Charles R. Swindoll" },
  { text: "Of course there is no formula for success except perhaps an unconditional acceptance of life and what it brings.", author: "Arthur Rubinstein" },
  { text: "Blaze with the fire that is never extinguished.", author: "Luisa Sigea" },
  { text: "Don't frown because you never know who is falling in love with your smile.", author: "Sinvyest Tan" },
  { text: "Patience is a virtue but you will never ever accomplish anything if you don't exercise action over patience.", author: "Byron Pulsifer" },
  { text: "You can adopt the attitude there is nothing you can do, or you can see the challenge as your call to action.", author: "Catherine Pulsifer" },
  { text: "If you spend too much time thinking about a thing, you'll never get it done.", author: "Bruce Lee" },
  { text: "No yesterdays are ever wasted for those who give themselves to today.", author: "Brendan Francis" },
  { text: "Until you make peace with who you are, you will never be content with what you have.", author: "Doris Mortman" },
  { text: "Yesterday I dared to struggle. Today I dare to win.", author: "Bernadette Devlin" },
  { text: "Life is what you make of it. Always has been, always will be.", author: "Grandma Moses" },
  { text: "Ignorance never settle a question.", author: "Benjamin Disraeli" },
  { text: "Human beings, who are almost unique in having the ability to learn from the experience of others, are also remarkable for their apparent disinclination to do so.", author: "Douglas Adams" },
  { text: "It is difficult to achieve a spirit of genuine cooperation as long as people remain indifferent to the feelings and happiness of others.", author: "Dalai Lama" },
  { text: "Not every difficult and dangerous thing is suitable for training, but only that which is conducive to success in achieving the object of our effort.", author: "Epictetus" },
  { text: "Work out your own salvation. Do not depend on others.", author: "Buddha" },
  { text: "What is not started today is never finished tomorrow.", author: "Goethe" },
  { text: "The truth of the matter is that you always know the right thing to do. The hard part is doing it.", author: "Norman Schwarzkopf" },
  { text: "If we learn to open our hearts, anyone, including the people who drive us crazy, can be our teacher.", author: "Pema Chodron" },
  { text: "The path to success is to take massive, determined action.", author: "Tony Robbins" },
  { text: "Those who dream by day are cognizant of many things which escape those who dream only by night.", author: "Edgar Allan Poe" },
  { text: "If you love someone, set them free. If they come back they're yours; if they don't they never were.", author: "Richard Bach" },
  { text: "Things do not change, we change.", author: "Henry Thoreau" },
  { text: "Speak when you are angry and you will make the best speech you will ever regret.", author: "Ambrose Bierce" },
  { text: "The reasonable man adapts himself to the world; the unreasonable man persists in trying to adapt the world to himself. Therefore, all progress depends on the unreasonable man.", author: "George Shaw" },
  { text: "Study the past, if you would divine the future.", author: "Confucius" },
  { text: "Every great mistake has a halfway moment, a split second when it can be recalled and perhaps remedied.", author: "Pearl Buck" },
  { text: "Change will not come if we wait for some other person or some other time. We are the ones weve been waiting for. We are the change that we seek.", author: "Barack Obama" },
  { text: "People grow through experience if they meet life honestly and courageously. This is how character is built.", author: "Eleanor Roosevelt" },
  { text: "Mistakes are always forgivable, if one has the courage to admit them.", author: "Bruce Lee" },
  { text: "Complaining doesn't change a thing only taking action does.", author: "Byron Pulsifer" },
  { text: "A man of ability and the desire to accomplish something can do anything.", author: "Donald Kircher" },
  { text: "Before you can inspire with emotion, you must be swamped with it yourself. Before you can move their tears, your own must flow. To convince them, you must yourself believe.", author: "Winston Churchill" },
]
